### ISSUE TITLE
Launch checklist

### ISSUE THREAD

**Issue by freekmurze** [spatie/laravelpackage.training#9]
We launch on Wednesday 27/5

## 1. Browserstack tests
- [x] Desktop: test on latest versions of Chrome, Edge, Firefox, Safari
- [x] Mobile: test on latest versions of Mobile Safari, Android

### Assets
- [x] Search sources for `http://`. Replace by `https://`
- [x] Lint (s)css sources
- [x] Webfonts: is the live domain configured in services like Typekit, Fonts.com etc.?
- [x] ~~Is the browserlist properly configured for autoprefixer and babel-preset-env?~~
- [x] When using PurgeCSS: check if layout is preserved.

### Scripts
- [x] Is `yarn.lock` present?
- [x] Check JS lint errors. Remove all `console.log` lines in scripts
- [x] Check for console errors

### Page weight
- [x] Evaluate total weight of at least homepage
- [x] Open Inspector network/timeline tab to identify heavy assets 
- [x] Check if heavy assets are cached 

### Audits
- [x] Use the Chrome DevTools (in incognito mode) and perform a mobile audit (with throttling) to fix common problems.
- [x] Repeat with a desktop audit.

## 3. Check content (with an open console)
- [x] Are all strings / images present (and translated)?
- [x] Does menu/submenu have a correct active state on every page?
- [x] Are 404, 500 and 503 pages provided? Do they provide useful content like 'back to home', search or a navigation tree?
- [x] Check all pages for n+1 problems

### Meta
- [x] Check page titles / descriptions
- [x] Test Facebook sharing. Provide og-tags if needed
- [x] Does Favicon load? Pin the tab in Safari to check pinned icon

_Repeat this section for all languages_

### Components
- [x] Try subscribing to a newsletter with incorrect & correct email (use correct mail twice to get 'already subscribed' message)
- [x] ~~Check layout of emails~~
- [x] ~~Check structured data for news, events, products,... https://search.google.com/structured-data/testing-tool/~~

## 4. Back end checklist
- [x] Try to create a new user and purchase the course, and verify that you can see the video

## 5. Server, DNS & Services
- [x] Add redirects from old to new pages if necessary.
- [x] Verify that indexing is not prohibited with `x-robots-tag: none` by checking `curl -I https://url | grep 'x-robots-tag'`. Allow robots in `.env`
- [x] Verify Tag Manager / Analytics have been correctly set up

### Google Search Console
- [x] Submit all www/non-www http/https variations
- [x] Set up non-www https as the preferred domain 
- [x] Crawl > Fetch as Google > Submit to index to kickstart index

### Server
- [x] Are DigitalOcean backups enabled?
- [x] Are Amazon backups enabled?
- [x] Is the output of artisan task `backup:run` ok?
- [x] Is artisan scheduled on Forge?
- [x] Is Horizon configured in Supervisor on Forge? Command should be `php artisan horizon`. Path should be `/home/forge/my-new-site.com/current`
- [x] Is the url being monitored by [Oh Dear!](https://ohdearapp.com/)?

### Other

- [x] add image ad to readme of all packages
- [x] add image ad to docs pages
